Repository the-collab-lab/website, pull requests merged in 2022-07, with the labels that each got.

#233 Fix NPM Vulnerabilities
  package-lock.json
Labels: dependencies, Redesign - Phase 1

#241 Fix Moving Arrows in Carousel
  pages/_includes/mlayout.liquid
  pages/assets/styles.css
Labels: enhancement

#242 feat: optimize JS asset delivery
  pages/_includes/mlayout.liquid
  pages/assets/scripts/donations/form.js
  pages/assets/scripts/donations/index.js
  pages/assets/scripts/donations/notification.js
  pages/assets/scripts/gallery.js
  pages/assets/scripts/toast.js
  pages/assets/styles/carousel.css
  pages/assets/styles/donations.css
  pages/assets/styles/members.css
  pages/assets/styles/styles.css
  pages/assets/styles/toast.css
  pages/assets/styles/volunteer.css
Labels: enhancement

#244 bug/Modify images paths
  pages/assets/styles/volunteer.css
Labels: bug
